/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
MumuAudioGranularAudioProcessorEditor::MumuAudioGranularAudioProcessorEditor (MumuAudioGranularAudioProcessor& p)
: AudioProcessorEditor (&p), processor (p), Tab(TabbedButtonBar::TabsAtLeft), button1("Grain")
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (600, 280);
    LookAndFeel::setDefaultLookAndFeel(&myLookAndFeel);
    
    addAndMakeVisible(Tab);
    Tab.setBounds(0, 20, 20, 180);
    Tab.addTab("Pitch / Stretch", Colour(Colours::darkgrey), 1);
    Tab.addTab("Rhythmic Chop", Colour(Colours::darkgrey), 2);
    Tab.addTab("Patches", Colour(Colours::darkgrey), 3);
    Tab.setAlpha(0.8);
    Tab.addChangeListener(this);
    
    PitchStretch.setBounds(20, 0, 580, 280);
    PitchStretch.addAndMakeVisible(Slider1);
    PitchStretch.addAndMakeVisible(Slider2);
    PitchStretch.addAndMakeVisible(Slider3);
    PitchStretch.addAndMakeVisible(Slider4);
    PitchStretch.addAndMakeVisible(Slider5);
    PitchStretch.addAndMakeVisible(button1);
    
    addChildComponent(PitchStretch);
    
    //Slider 1
    Slider1.setTextBoxStyle(Slider::NoTextBox, false, 0, 0);
    Slider1.setName("Slider 1");
    Slider1.setSliderStyle(Slider::RotaryVerticalDrag);
    Slider1.setRange(0.0, 1.0);
    Slider1.addListener(this);
    Slider1.setBounds(60, 28, 75, 75);
    
    Label1.setText("Pitch", dontSendNotification);
    Label1.setColour(juce::Label::textColourId, juce::Colour(255.0f, 255.0f, 255.0f));
    Label1.attachToComponent(&Slider1, true);
    
    Slider2.setTextBoxStyle(Slider::NoTextBox, false, 0, 0);
    Slider2.setName("Slider 2");
    Slider2.setSliderStyle(Slider::RotaryVerticalDrag);
    Slider2.setRange(0.0, 1.0);
    Slider2.addListener(this);
    Slider2.setBounds(160, 88, 75, 75);
    
    Label2.setText("Density", dontSendNotification);
    Label2.setColour(juce::Label::textColourId, juce::Colour(255.0f, 255.0f, 255.0f));
    Label2.attachToComponent(&Slider2, true);
    
    Slider3.setTextBoxStyle(Slider::NoTextBox, false, 0, 0);
    Slider3.setName("Slider 3");
    Slider3.setSliderStyle(Slider::RotaryVerticalDrag);
    Slider3.setRange(0.0, 1.0);
    Slider3.addListener(this);
    Slider3.setBounds(260, 28, 75, 75);
    
    Label3.setText("GrainSize", dontSendNotification);
    Label3.setColour(juce::Label::textColourId, juce::Colour(255.0f, 255.0f, 255.0f));
    Label3.attachToComponent(&Slider3, true);
    addAndMakeVisible(Label3);
    
    Slider4.setTextBoxStyle(Slider::NoTextBox, false, 0, 0);
    Slider4.setName("Slider 4");
    Slider4.setSliderStyle(Slider::RotaryVerticalDrag);
    Slider4.setRange(0.0, 1.0);
    Slider4.addListener(this);
    Slider4.setBounds(360, 88, 75, 75);
   // addAndMakeVisible(Slider4);
    
    Label4.setText("Dry/Wet", dontSendNotification);
    Label4.setColour(juce::Label::textColourId, juce::Colour(255.0f, 255.0f, 255.0f));
    Label4.attachToComponent(&Slider4, true);
    addAndMakeVisible(Label4);
    
    Slider5.setTextBoxStyle(Slider::NoTextBox, false, 0, 0);
    Slider5.setName("Slider 5");
    Slider5.setSliderStyle(Slider::RotaryVerticalDrag);
    Slider5.setRange(0.0, 1.0);
    Slider5.addListener(this);
    Slider5.setBounds(500, 88, 45, 45);
   // addAndMakeVisible(Slider5);
    
    Label5.setText("Speed", dontSendNotification);
    Label5.setColour(juce::Label::textColourId, juce::Colour(255.0f, 255.0f, 255.0f));
    Label5.attachToComponent(&Slider5, false);
    addAndMakeVisible(Label5);
    
    button1.setBounds(480,28,80,20);
    button1.setColour(juce::ToggleButton::textColourId , Colours::white);
    button1.addListener(this);
    
    addMouseListener(this, true);
    
    timerCallback();
    checkTabs();
    startTimer(50);
}

MumuAudioGranularAudioProcessorEditor::~MumuAudioGranularAudioProcessorEditor()
{
}

//==============================================================================
void MumuAudioGranularAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colour(30,30,30));
    g.setGradientFill(ColourGradient(Colour(255,255,255), 0, 0, Colour(211,211,211), 600, 0, false));
    //top rectangle
    g.fillRoundedRectangle(0,6,600,8,2);
    
    g.setGradientFill(ColourGradient(Colour(255,255,255), 0, 280, Colour(211,211,211), 300, 280, false));
    //lower rectangle & text
    //first half
    g.fillRoundedRectangle(0,263,370,8,2);
    //text
    g.setColour(Colour(uint8(211),uint8(211),uint8(211),float(1)));
    g.setFont (Font("Arial", 10, Font::bold + Font::italic));
    g.drawSingleLineText(" Mumu[Audio] | MNML Granular | CalArts MTIID", 370, 270);
    //second rect
    g.fillRoundedRectangle(572,263,26,8,2);
    
    Image Logo = ImageCache::getFromMemory(BinaryData::MumuLight_png, BinaryData::MumuLight_pngSize);
    //g.drawImageAt(Logo, 10, 40);
    g.drawImage(Logo, 10, 218, 65, 35, 0, 0, 115, 65);
    Image MTIID = ImageCache::getFromMemory(BinaryData::MTIID_png, BinaryData::MTIID_pngSize);
    //g.drawImageAt(Logo, 10, 40);
    g.drawImage(MTIID, 83, 220, 85, 30, 0, 0, 190, 95);
    
    //vert
    g.fillRoundedRectangle(171,208,1,55,0);
    //horizontal
    g.fillRoundedRectangle(0,208,600,1,0);
}

void MumuAudioGranularAudioProcessorEditor::timerCallback(){
    Slider1.setValue(processor.slider1Param->getValue(), dontSendNotification);
    Slider2.setValue(processor.slider2Param->getValue(), dontSendNotification);
    Slider3.setValue(processor.slider3Param->getValue(), dontSendNotification);
    Slider4.setValue(processor.slider4Param->getValue(), dontSendNotification);
    Slider5.setValue(processor.slider5Param->getValue(), dontSendNotification);
    Tab.setCurrentTabIndex(processor.currentTab->getValue(), dontSendNotification);
}

void MumuAudioGranularAudioProcessorEditor::sliderValueChanged (Slider* sliderThatHasChanged){
    
    if (sliderThatHasChanged == &Slider1) {
        processor.slider1Param->beginChangeGesture();
        processor.slider1Param->setValueNotifyingHost(sliderThatHasChanged->getValue());
        processor.slider1Param->endChangeGesture();
    }
    if (sliderThatHasChanged == &Slider2) {
        processor.slider2Param->beginChangeGesture();
        processor.slider2Param->setValueNotifyingHost(sliderThatHasChanged->getValue());
        processor.slider2Param->endChangeGesture();
    }
    if (sliderThatHasChanged == &Slider3) {
        processor.slider3Param->beginChangeGesture();
        processor.slider3Param->setValueNotifyingHost(sliderThatHasChanged->getValue());
        processor.slider3Param->endChangeGesture();
    }
    if (sliderThatHasChanged == &Slider4) {
        processor.slider4Param->beginChangeGesture();
        processor.slider4Param->setValueNotifyingHost(sliderThatHasChanged->getValue());
        processor.slider4Param->endChangeGesture();
    }
    if (sliderThatHasChanged == &Slider5) {
        processor.slider5Param->beginChangeGesture();
        processor.slider5Param->setValueNotifyingHost(sliderThatHasChanged->getValue());
        processor.slider5Param->endChangeGesture();
    }
}

void MumuAudioGranularAudioProcessorEditor::mouseDown(const MouseEvent & e) {
    if ( e.eventComponent->getName() == Slider1.getName() || e.eventComponent->getName() == Slider2.getName() || e.eventComponent->getName() == Slider3.getName() || e.eventComponent->getName() == Slider4.getName() || e.eventComponent->getName() == Slider5.getName() ){
        e.source.enableUnboundedMouseMovement(true);
    }
}

void MumuAudioGranularAudioProcessorEditor::buttonClicked(juce::Button *button){
    if (button == &button1)
    {
        processor.button1Param->setValueNotifyingHost(button1.getToggleState());
    }
}

void MumuAudioGranularAudioProcessorEditor::changeListenerCallback(juce::ChangeBroadcaster *source){
    checkTabs();
}

void MumuAudioGranularAudioProcessorEditor::checkTabs(){
    if (Tab.getCurrentTabIndex() == 0)
    {
        PitchStretch.setVisible(true);
        processor.currentTab->setValueNotifyingHost(0);
    }
    else if (Tab.getCurrentTabIndex() == 1)
    {
        PitchStretch.setVisible(false);
        processor.currentTab->setValueNotifyingHost(1);
    }
    else if (Tab.getCurrentTabIndex() == 2)
    {
        PitchStretch.setVisible(false);
        processor.currentTab->setValueNotifyingHost(2);
    }
}


