/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "CustomLookAndFeel.h"
#include "AudioLiveScrollingDisplay.h"



//==============================================================================
/**
*/
class MumuAudioGranularAudioProcessorEditor  :  public AudioProcessorEditor,
                                                public Slider::Listener,
                                                public Button::Listener,
                                                public Timer
                                                //public TabbedComponent
{
public:
    MumuAudioGranularAudioProcessorEditor (MumuAudioGranularAudioProcessor&);
    ~MumuAudioGranularAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    
    void timerCallback() override;
    void sliderValueChanged (Slider* sliderThatHasChanged) override;
    
    void buttonClicked (Button* button) override;
    
    
    void mouseDown (const MouseEvent &e) override;
    void mouseUp (const MouseEvent &e) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    MumuAudioGranularAudioProcessor& processor;
    
    
    Slider Slider1;
    Slider Slider2;
    Slider Slider3;
    Slider Slider4;
    Slider Slider5;
    
    Label Label1;
    Label Label2;
    Label Label3;
    Label Label4;
    Label Label5;
    
    ToggleButton button1;
    
    CustomLookAndFeel myLookAndFeel;
    

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MumuAudioGranularAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
