/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "Granulator.h"
#include "GranularBuffer.h"
#include "GrainScheduler.h"
#include "Grain.h"
#include "EnvelopeGenerator.h"

//==============================================================================
/**
*/
class MumuAudioGranularAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    MumuAudioGranularAudioProcessor();
    ~MumuAudioGranularAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    const String getName() const override;

    const String getInputChannelName (int channelIndex) const override;
    const String getOutputChannelName (int channelIndex) const override;
    bool isInputChannelStereoPair (int index) const override;
    bool isOutputChannelStereoPair (int index) const override;

    bool acceptsMidi() const override;
    bool producesMidi() const override;
    bool silenceInProducesSilenceOut() const override;
    double getTailLengthSeconds() const override;

    //==============================================================================
    int getNumPrograms() override;
    int getCurrentProgram() override;
    void setCurrentProgram (int index) override;
    const String getProgramName (int index) override;
    void changeProgramName (int index, const String& newName) override;

    //==============================================================================
    void getStateInformation (MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;
    
    //Current Tab
    AudioProcessorParameter* currentTab;
    
    //Tab 1 Params
    AudioProcessorParameter* Tab1_pitchKnobParam;
    AudioProcessorParameter* Tab1_densityKnobParam;
    AudioProcessorParameter* Tab1_grainSizeKnobParam;
    AudioProcessorParameter* Tab1_dryWayKnobParam;
    AudioProcessorParameter* Tab1_stretchSpeedKnobParam;
    AudioProcessorParameter* Tab1_stretchButtonParam;
    
//    std::atomic<bool> guiUpToDate;
//    std::shared_ptr<AudioSampleBuffer> sharedSampleBuffer;

    
private:
    //Function to map our knob parameters
    void updateParams();
    //Mapped param variables
    float pitch;
    float density;
    float grainSize;
    float dryWet;
    int buttonState;
    float stretchSpeed;
    //Top Grain Container
    Granulator m_GranulatorL;
    Granulator m_GranulatorR;
    //Buffers for Granulation
    GranularBuffer m_gBufferL;
    GranularBuffer m_gBufferR;
    const float m_fMaxBufferLength = 10.0;
    //Clocks for driving Granulator
    GrainScheduler m_SchedulerL;
    GrainScheduler m_SchedulerR;
    //Array of grains to play buffers
    const int m_nNumberGrains = 6;
    Grain* grainp_ArrayL;
    Grain* grainp_ArrayR;
    
    float m_fSampleRate;
    
    EnvelopeGenerator m_ADSR_Left;
    int m_ADSR_Left_Started;
    float stretchDeltaL;
    
    EnvelopeGenerator m_ADSR_Right;
    int m_ADSR_Right_Started;
    float stretchDeltaR;
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MumuAudioGranularAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
