/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "CustomLookAndFeel.h"
#include "AudioLiveScrollingDisplay.h"



//==============================================================================
/**
*/
class MumuAudioGranularAudioProcessorEditor  :  public AudioProcessorEditor,
                                                public Slider::Listener,
                                                public Button::Listener,
                                                public ChangeListener,
                                                public Timer
{
public:
    MumuAudioGranularAudioProcessorEditor (MumuAudioGranularAudioProcessor&);
    ~MumuAudioGranularAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    
    void timerCallback() override;
    void sliderValueChanged (Slider* sliderThatHasChanged) override;
    
    void buttonClicked (Button* button) override;
    
    
    void mouseDown (const MouseEvent &e) override;
    
    void changeListenerCallback(ChangeBroadcaster *source) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    MumuAudioGranularAudioProcessor& processor;
    //===== Tab Bar Object =====
    TabbedButtonBar Tab;
    void checkTabs();
    //======== Tab 1 ===========
    Component PitchStretch;
    
    Slider Tab1_pitchKnob;
    Slider Tab1_densityKnob;
    Slider Tab1_grainSizeKnob;
    Slider Tab1_dryWayKnob;
    Slider Tab1_stretchSpeedKnob;
    
    Label Tab1_pitchLabel;
    Label Tab1_densityLabel;
    Label Tab1_grainSizeLabel;
    Label Tab1_dryWetLabel;
    Label Tab1_stretchSpeedLabel;
    
    ToggleButton Tab1_stretchButton;
    
    
    
    //===== Look And Feel ======
    CustomLookAndFeel myLookAndFeel;
    
    

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MumuAudioGranularAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
