/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class MumuAudioGranularAudioProcessorEditor  : public AudioProcessorEditor,
                                               public Slider::Listener,
                                               public Timer
{
public:
    MumuAudioGranularAudioProcessorEditor (MumuAudioGranularAudioProcessor&);
    ~MumuAudioGranularAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    
    void timerCallback() override;
    void sliderValueChanged (Slider* sliderThatHasChanged) override;
    
    void mouseDown (const MouseEvent &e) override;
    void mouseUp (const MouseEvent &e) override;

private:
    Slider Slider1;
    Slider Slider2;
    Slider Slider3;
    Slider Slider4;
    
    TextButton button1;
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    MumuAudioGranularAudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MumuAudioGranularAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
